theme = "gruvbox_light"

[editor]
line-number = "absolute"
mouse = true
auto-completion = false
auto-format = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true
auto-signature-help = false
display-signature-help-docs = false

[editor.file-picker]
hidden = false
